### ISSUE TITLE
Auth prompt

### ISSUE THREAD

**Issue by GuillaumeAmat** [abricot/foxmote#4]
When we navigate in libraries (i.e. videos, musics), the auth prompt pops out (HTTP Auth).
Why not register the credentials and get rid of this annoying prompt ?

**Comment by nicolasabric** [comment]
I never saw this behavior before. Have you activated any kind of security? Could you share your set-up ?

**Comment by GuillaumeAmat** [comment]
Weird... It pops out on my laptop, my desktop, and my android device. So it doesn't seem to be a client issue.
The only security I have is the password in the web kodi setup.

**Comment by nicolasabric** [comment]
OK I will setup a password as well and see if I experience the same issue.

**Comment by nicolasabric** [comment]
Version 2.1.0 will contain the above fix. Could you please give it a try and let me know if it resolve the issue.

**Comment by GuillaumeAmat** [comment]
It's working like a charm, thanks!
