### ISSUE TITLE
Auto-load more datas when scrolling the page

### ISSUE THREAD

**Issue by GuillaumeAmat** [abricot/foxmote#5]
Currently there is limits to datas retrieved from Kodi :
* 100 artists and albums
* 500 songs
* 75 TV shows, seasons, episodes and films

So when the user library is more important than these limits, he can't browse the totality.
A fix could be to retrieve more datas when the user is scrolling the lists of songs, artists and so on.

**Comment by nicolasabric** [comment]
Indeed that's something that can be implemented. One solution might be to use an infinite scroll linked to the limit attribute of any getXXX function. I will have a look at it.

**Comment by nicolasabric** [comment]
Version 2.1.0 will contain the above fix. Could you please give it a try and let me know if it resolve the issue.

**Comment by GuillaumeAmat** [comment]
This update will be available in the marketplace or I have to manually install it?

**Comment by nicolasabric** [comment]
The chrome app has been already released and deployed. The firefox os app is in "Pending approval" status. From my experience it can take up to 5 days for the app to be approved. I will monitor the submission process and add a comment here when the version will be released.

**Comment by GuillaumeAmat** [comment]
It's working like a charm, thanks!
