### ISSUE TITLE
Retrieve the actual volume before modify it

### ISSUE THREAD

**Issue by GuillaumeAmat** [abricot/foxmote#6]
When I want to raise the volume, it's set to the minimum before the raise.
It would be better to retrieve the actual volume when foxmote starts, then raise it from that level.

**Comment by nicolasabric** [comment]
Version 2.1.1 will contain the above fix. Could you please give it a try and let me know if it resolve the issue. Chrome app is already deployed, Firefox OS app is "Pending approval"

**Comment by GuillaumeAmat** [comment]
The volume is not lost anymore but after the first modification of the volume +1 or -1), I cannot do any other modification...
