### ISSUE TITLE
It's not working with v15

### ISSUE THREAD

**Issue by NerosTie** [abricot/foxmote#7]
Arch is not working with Kodi version 15 (and it's not in the new repo).

**Comment by nicolasabric** [comment]
@NerosTie I m guessing that you meant to open this issue on the Arch repo but that's ok. 

The new version of Arch (2.0.0) is under review by the Kodi team. It should be available  in the coming days in the official Isengard repo (Kodi 15). In the mean time if you already migrated to version 15 and want to keep using Arch you can install the zip file located here https://db.tt/zDZpWIiB. Once you download the zip just install it using "install from zip file" functionality under Settings>Add-ons.

Cheers

**Comment by NerosTie** [comment]
Sorry for the wrong repo!  
And thank you for your answer :)
